import { Config } from '../../interfaces';

export const configTemplate: Config = {
  WEATHER_API_KEY: '',
  lat: 0,
  long: 0,
  isCelsius: true,
  customTitle: 'Flame',
  pinAppsByDefault: true,
  pinBookmarksByDefault: true,
  pinCategoriesByDefault: true,
  hideHeader: false,
  useOrdering: 'createdAt',
  appsSameTab: false,
  bookmarksSameTab: false,
  searchSameTab: false,
  hideApps: false,
  hideBookmarks: false,
  hideEmptyCategories: true,
  hideSearch: false,
  defaultSearchProvider: 'l',
  secondarySearchProvider: 'd',
  dockerApps: false,
  dockerHost: 'localhost',
  kubernetesApps: false,
  unpinStoppedApps: false,
  hideGreeting: false,
  disableAutofocus: false,
  greetingsSchema: 'Good evening!;Good afternoon!;Good morning!;Good night!',
  daySchema: 'Sun;Mon;Tue;Wed;Thu;Fri;Sat',
  monthSchema: 'Jan;Feb;Mar;Apr;May;Jun;Jul;Aug;Sep;Oct;Nov;Dec',
  showTime: false,
  defaultTheme: 'tron',
  isKilometer: true,
  weatherData: 'cloud',
  hideDate: false,
};
